<?php

return [
    'industria' => [
        'name' => 'Industria',
        'accent' => 'industria',
        'accent_soft' => 'industria-soft',
        'headline' => 'Transformamos necesidades industriales en soluciones reales.',
        'tagline' => 'En Innovet, somos especialistas en diseñar y fabricar piezas termoformadas que se ajustan a las necesidades particulares de cada industria.',
        'subheadline' => null,
        'cta_label' => 'Conocer Industria',
        'reference' => 'https://innovet.com.mx/',
        'visual_keywords' => ['Manufactura', 'Maquinaria', 'Piezas industriales', 'Ingeniería'],
        'image' => 'img/innovet-card.webp',  
        'logo' => 'logo/innovet-logo.png',
        'background_image' => 'img/innovet/background.webp',
        'capabilities' => [
            [
                'label' => 'Charolas',
                'image' => 'img/innovet/charola.webp',
                'advantages' => [
                    'Se diseña y fabrica para atender necesidades específicas.',
                    'Uso interno entre líneas de producción, traslado de piezas y entrega final. ',
                    'Piezas de un solo uso o retornables.',
                    'Diseños de estibas apilables para un manejo y almacenamiento eficiente.',
                ],
            ],
            [
                'label' => 'Blisters',
                'image' => 'img/innovet/blister.webp',
                'advantages' => [
                    'Garantiza la seguridad y preservación de tus productos desde la línea de producción hasta el almacenamiento y la entrega final.',
                    'Cada proyecto es único y se diseña y fabrica de manera exclusiva para satisfacer tus necesidades',
                    'Realza las características de tus productos en los puntos de venta, impulsando su atractivo visual',
                    'Mantén en perfecto estado y protegido contra daños y pérdidas.',
                ],
            ],
            [
                'label' => 'Clamshells',
                'image' => 'img/innovet/clamshell.jpeg',
                'advantages' => [
                    'Empaque tipo concha que permite ver el producto desde todos los ángulos.',
                    'Cierre a presión que facilita el empaque y desempaque sin herramientas.',
                    'Alta resistencia a la manipulación, ideal como protección antirrobo en retail.',
                    'Contenedores con dos o más secciones que se pliegan mediante una bisagra.',
                ],
            ],
        ],
        'materials' => [
            ['label' => 'ESD', 'description' => 'Material antiestático', 'image' => 'img/innovet/materials/esd.webp'],
            ['label' => 'HDPE', 'description' => 'Polietileno de alta densidad', 'image' => 'img/innovet/materials/hdpe.webp'],
            ['label' => 'PET', 'description' => 'Tereftalato de polietileno', 'image' => 'img/innovet/materials/pet.webp'],
            ['label' => 'PP', 'description' => 'Polipropileno', 'image' => 'img/innovet/materials/pp.webp'],
            ['label' => 'PS', 'description' => 'Poliestireno', 'image' => 'img/innovet/materials/ps.webp'],
            ['label' => 'HIPS', 'description' => 'Poliestireno de alto impacto', 'image' => 'img/innovet/materials/hips.webp'],
            ['label' => 'De barrera', 'description' => 'Material de barrera', 'image' => 'img/innovet/materials/barrera.webp'],
        ],
        'industries_served' => [
            [
                'label' => 'Alimenticia',
                'icon' => 'food',
                'image' => 'img/innovet/industries/alimenticia.webp',
                'description' => 'Envases y charolas termoformadas que preservan frescura y cumplen normativas de contacto alimentario.',
            ],
            [
                'label' => 'Automotriz',
                'icon' => 'car',
                'image' => 'img/innovet/industries/automotriz.webp',
                'description' => 'Ayudan a prevenir daños durante el almacenamiento y el envío, lo que es crucial para mantener la calidad de las piezas.',
            ],
            [
                'label' => 'Agroindustrial',
                'icon' => 'leaf',
                'image' => 'img/innovet/industries/agroindustrial.webp',
                'description' => 'Ayudan a mantener la frescura y la integridad de los productos durante su distribución',
            ],
            [
                'label' => 'Electrónica',
                'icon' => 'chip',
                'image' => 'img/innovet/industries/electronica.webp',
                'description' => 'Ofrecen protección a componentes frágiles como placas de circuitos y chips. Su diseño personalizado garantiza un ajuste perfecto',
            ],
            [
                'label' => 'Retail',
                'icon' => 'bag',
                'image' => 'img/innovet/industries/retail.webp',
                'description' => 'Protegen y destacan el producto, asegurando su integridad y mejorando la experiencia del cliente en el punto de venta.',
            ],
            [
                'label' => 'Farmacéutica',
                'icon' => 'cross',
                'image' => 'img/innovet/industries/farmaceutica.webp',
                'description' => 'Proporcionan un empaque resistente a la humedad y a la contaminación.',
            ],
            [
                'label' => 'Cosmética',
                'icon' => 'droplet',
                'image' => 'img/innovet/industries/cosmetica.webp',
                'description' => 'Permiten un mayor cuidado y control sobre aquellos productos delicados.',
            ],
        ],
    ],

    'logistica' => [
        'name' => 'Logística',
        'accent' => 'logistica',
        'accent_soft' => 'logistica-soft',
        'headline' => 'Soluciones en logística, almacenaje y transporte terrestre',
        'tagline' => 'En Upper Logistics somos líderes en gestión y optimización de la cadena de suministro. Con un firme enfoque en innovación logística y eficiencia operativa.',
        'subheadline' => null,
        'cta_label' => 'Conocer Logística',
        'reference' => 'https://upperlogistics.mx/',
        'visual_keywords' => ['Almacenes', 'Transporte', 'Distribución', 'Tecnología logística'],
        'image' => 'img/upper-card.webp',
        'logo' => 'logo/upper-logo.png',
        'background_image' => 'img/upper/backgroundU.webp',
        'capabilities' => [
            'Almacenaje', 'Agencia Aduanal', 'Desconsolidación', 'Cross Docking',
            'Flete terrestre', '3PL',
        ],
    ],

    'inmobiliaria' => [
        'name' => 'Inmobiliaria',
        'accent' => 'inmobiliaria',
        'accent_soft' => 'inmobiliaria-soft',
        'headline' => 'Tu proyecto. De la idea a la realidad.',
        'tagline' => 'Desarrollamos proyectos inmobiliarios empresariales llave en mano, desde la planeación hasta la entrega.',
        'subheadline' => 'Desarrollamos proyectos empresariales llave en mano, integrando planeación, diseño, construcción y entrega bajo una misma visión.',
        'cta_label' => 'Conocer Inmobiliaria',
        'reference' => null,
        'visual_keywords' => ['Edificios', 'Parques industriales', 'Arquitectura', 'Infraestructura'],
        'background_image' => 'img/inmobiliaria/inmobiliariaBack.jpg',
        'image' => 'img/inmobiliaria-card.webp',
        'process' => [
            ['step' => '01', 'label' => 'Planeación'],
            ['step' => '02', 'label' => 'Diseño'],
            ['step' => '03', 'label' => 'Ingeniería'],
            ['step' => '04', 'label' => 'Construcción'],
            ['step' => '05', 'label' => 'Equipamiento'],
            ['step' => '06', 'label' => 'Entrega'],
        ],
        'project_placeholders' => [
            ['label' => 'Parques industriales', 'image' => 'img/inmobiliaria/tipos/parques-industriales.webp'],
            ['label' => 'Centros de distribución', 'image' => 'img/inmobiliaria/tipos/centros-distribucion.webp'],
            ['label' => 'Infraestructura empresarial', 'image' => 'img/inmobiliaria/tipos/infraestructura-empresarial.webp'],
        ],
    ],

];
